// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtrfakshijejxmuhyjbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10cmZha3NoaWplanhtdWh5amJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTEwMDQsImV4cCI6MjA2OTM4NzAwNH0.nkYooa6u6n7K0MtlYuTLjnI4eq8wq81uoZAWDe6aras";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});